### ISSUE TITLE
Shared Clipboard for Anbox and Ubuntu Touch

### ISSUE THREAD

**Issue by tv0ll** [ubports/anbox#33]
```
version: local-/bin/sh: 1: git: not found
cpu:
 arch:
 brand:
 features:
os:
 name: Ubuntu
 version: 16.04.5 LTS (Xenial Xerus)
 snap-based: false
kernel:
 version: Linux version 3.4.0-Sultan-CAF (mariogrip@mariogrip-elem) (gcc version 4.8 (GCC) ) #2 SMP PREEMPT Sat Aug 11 19:42:30 CEST 2018
 binder: true
 ashmem: true
graphics:
 egl:
   vendor: Android
   version: 1.4 Android META-EGL
   extensions:
     - EGL_KHR_get_all_proc_addresses
     - EGL_ANDROID_presentation_time
     - EGL_KHR_image
     - EGL_KHR_image_base
     - EGL_KHR_lock_surface
     - EGL_KHR_gl_texture_2D_image
     - EGL_KHR_gl_texture_cubemap_image
     - EGL_KHR_gl_renderbuffer_image
     - EGL_KHR_fence_sync
     - EGL_KHR_create_context
     - EGL_EXT_create_context_robustness
     - EGL_ANDROID_image_native_buffer
     - EGL_KHR_wait_sync
     - EGL_ANDROID_recordable
     - EGL_HYBRIS_native_buffer2
     - EGL_HYBRIS_WL_acquire_native_buffer
     - EGL_WL_bind_wayland_display
 gles2:
   vendor: n/a
   vendor: OpenGL ES 2.0 ((null))
   extensions:
     - n/a
```

**Please describe your problem:**
Cannot copy from Ubuntu Touch and paste within any Anbox app.

**What were you expecting?:**
Was expecting a shared clipboard to make the integration of Anbox apps and Ubuntu Touch more seamless.

**Additional info:**
Without out this, it can get very frustrating for a user using a Password Manager with an array of long passwords.
