### ISSUE TITLE
Nexus 7 (2013) (deb) Anbox doesn't work

### ISSUE THREAD

**Issue by ameyagokhale** [ubports/anbox#42]
** Please paste the result of `anbox system-info` below:**
```
phablet@ubuntu-phablet:~$ anbox system-info
version: local-/bin/sh: 1: git: not found
cpu:
  arch:
  brand:
  features:
os:
  name: Ubuntu
  version: 16.04.7 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 3.4.0+ (ubuntu@M4Master) (gcc version 4.9.3 (Ubuntu/Linaro 4.9.3-13ubuntu2) ) #3 SMP PREEMPT Fri Sep 25 11:53:44 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Android
    version: 1.4 Android META-EGL
    extensions:
      - EGL_KHR_get_all_proc_addresses
      - EGL_ANDROID_presentation_time
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_lock_surface
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_fence_sync
      - EGL_KHR_create_context
      - EGL_EXT_create_context_robustness
      - EGL_ANDROID_image_native_buffer
      - EGL_KHR_wait_sync
      - EGL_ANDROID_recordable
      - EGL_HYBRIS_native_buffer2
      - EGL_HYBRIS_WL_acquire_native_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: OpenGL ES 2.0 ((null))
    extensions:
      - n/a
```

**Please describe your problem:**
With the help of @UniversalSuperBox I was able to prepare Modified boot.img for N7 2013 (deb)
Modified Kernel code of `deb/flo`:  https://github.com/ameyagokhale/ubuntu_kernel_xenial/tree/flo

When I try to execute anbox-tool install I get this:

    phablet@ubuntu-phablet:~$ anbox-tool install
    /home/phablet/anbox 100%[===================>] 207.16M  4.32MB/s    in 45s
    start: Job failed to start
    start: Unknown job: anbox-session
    
    
    ^CTraceback (most recent call last):
      File "/usr/bin/anbox-tool", line 329, in <module>
        enable()
      File "/usr/bin/anbox-tool", line 192, in enable
        waitForAnbox()
      File "/usr/bin/anbox-tool", line 180, in waitForAnbox
        time.sleep(1)
    KeyboardInterrupt

Anbox-tool status shows this:

    phablet@ubuntu-phablet:~/anbox-data$ anbox-tool status
    Kernel: OK
    System: OK
    Enabled: YES
    Running: NO

Output of lxc-console

    phablet@ubuntu-phablet:~$ sudo lxc-console -ndefault -P /home/phablet/anbox-data/containers -t0
    default is not running

Due to which adb devices shows nothing:

    phablet@ubuntu-phablet:~$ adb devices
    List of devices attached
    
    phablet@ubuntu-phablet:~$

Already tried rebooting but that didn't help.

Also tried disabling/enabling anbox:

    phablet@ubuntu-phablet:~$ anbox-tool disable
    Anbox is alredy disabled
	
    phablet@ubuntu-phablet:~$ sudo anbox-tool enable
    start: Job failed to start
    start: Unknown job: anbox-session
	
    ^CTraceback (most recent call last):
      File "/usr/bin/anbox-tool", line 329, in <module>
        enable()
      File "/usr/bin/anbox-tool", line 192, in enable
        waitForAnbox()
      File "/usr/bin/anbox-tool", line 180, in waitForAnbox
        time.sleep(1)
    KeyboardInterrupt
	
    phablet@ubuntu-phablet:~$ sudo anbox-tool status
    Kernel: OK
    System: OK
    Enabled: YES
    Running: NO
	
    phablet@ubuntu-phablet:~$ sudo anbox-tool disable
    stop: Unknown job: anbox-session
    stop: Unknown instance:
    Anbox is now disabled
	
	phablet@ubuntu-phablet:~$ 

**What were you expecting?:**

The container should be visible in `adb devices` (anbox should work) and I should be able to install and use Android Apps.

**Additional info:**
